module Foreman::Controller::Conflict
  def self.included(base)
      base.class_eval do
        before_filter :load_collision, :only => [:repair, :overwrite]
        # We need to use a different name for the filter otherwise the :only argument cannot be applied
        alias_method :find_by_name_for_compare, :find_by_name
        before_filter :find_by_name_for_compare, :only => :compare
        after_filter  :clear_collision, :except => [:compare, :update, :create]
      end
  end

  # Called when an Update or Create operation conflicted with an already present
  # network database entry and the user has responded "overwrite network entries"
  def overwrite
    load_vars_for_ajax
    forward_request_url
    if @host.repair()
      if @host.save
        notice "Successfully created host"
        redirect_to @host
      else
        render :action => :new
      end
    else
      error "Failed to clear conflicting network entries"
      render :action => :new
    end
  end

  # Called from the host's edit page when the "repair" button is clicked. Compares the
  # Host's network database entries with the values held in the host itself. It stores
  # the result of this comparison in the host.collision object and the session
  def compare
    return unless @host

    session[:collision] = @host.collisions(true)
    if @host.errors.empty?
      render :partial => "conflict", :locals => {:collision => @host.collision}
    else
      render :text => "Network Query failed.<br>" + @host.errors.full_messages.join("<br>")
    end
  rescue => e
    render :text => "Network Query failed. Please inspect the logs..."
  end

  # Called from the host's conflicts page, as generated by the "repair" button
  # Resolve the host's conflicts and adds missing data to the network databases
  # @host contains the host built from the session's collision item
  def repair
    # The return code triggers an alert in the user's browser showing the status
    # of the operation.
    if @host.repair()
      head 200
    else
      head 400
    end
  ensure
    session[:collision] = nil
  end

  private
  # Before_filter that is responsible for loading a collision object from the session and locating
  # the host that was associated with it. Note that the collision.host object is not an ActiveRecord Host
  def load_collision
  # Using a session variable ensures that we provide no API to directly modify network databases
    collision = session[:collision]
    # Let us be very sure that we are operating on the same collision object
    unless ((collision.check == params[:remove][:check].to_i ) rescue nil)
      error "Unable to proceed. Something went wrong with the session's collision object."
      redirect_to hosts_path
      return false
    end
    attributes = collision.host.marshal_dump
    attributes.delete :environment # Why do I have to do this?
    # The host may be a new or an edited host
    @host = Host.find_or_initialize_by_id(attributes[:id], attributes)
    @host.collision = collision
  end

  def clear_collision
    session[:collision] = nil
  end

end
